# Generated by Django 4.2.1 on 2024-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_tag_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
